Update Linux

diff --git a/Linux b/Linux
--- a/Linux
+++ b/Linux
@@ -1,13 +1,13 @@
 # Linux
-📌 Tasks<br>
-1️⃣ User & Group Management<br>
-Learn about Linux users, groups, and permissions (/etc/passwd, /etc/group).<br>
+📌 Tasks
+1️⃣ User & Group Management
+Learn about Linux users, groups, and permissions (/etc/passwd, /etc/group).
 Task:<br>
-Create a user devops_user and add them to a group devops_team.<br>
-Set a password and grant sudo access.<br>
-Restrict SSH login for certain users in /etc/ssh/sshd_config.<br>
-2️⃣ File & Directory Permissions<br>
-Task:<br>
+Create a user devops_user and add them to a group devops_team.
+Set a password and grant sudo access.
+Restrict SSH login for certain users in /etc/ssh/sshd_config.
+2️⃣ File & Directory Permissions
+Task:
 Create /devops_workspace and a file project_notes.txt.<br>
 Set permissions:<br>
 Owner can edit, group can read, others have no access.<br>
@@ -42,101 +42,101 @@ New password:<br>
 Retype new password:<br>
 passwd: password updated successfully<br>
 
-🔹 Verify current user & switch to new user<br>
-ubuntu@ip-172-31-36-175:~$ whoami<br>
+🔹 Verify current user & switch to new user
+ubuntu@ip-172-31-36-175:~$ whoami
 ubuntu<br>
 
-ubuntu@ip-172-31-36-175:~$ su devops_user<br>
-Password:<br>
-$ whoami<br>
-devops_user<br>
+ubuntu@ip-172-31-36-175:~$ su devops_user
+Password:
+$ whoami
+devops_user
 
 **✅ 2. File & Directory Permissions**<br>
 
 🔹 Create workspace and file<br>
 ubuntu@ip-172-31-36-175:~$ mkdir devops_workspace<br>
 ubuntu@ip-172-31-36-175:~$ cd devops_workspace<br>
-ubuntu@ip-172-31-36-175:~/devops_workspace$ touch project_notes.txt<br>
+ubuntu@ip-172-31-36-175:~/devops_workspace$ touch project_notes.txt
 
 🔹 Check default permissions<br>
-ubuntu@ip-172-31-36-175:~/devops_workspace$ ls -l<br>
-total 0<br>
--rw-rw-r-- 1 ubuntu ubuntu 0 Nov 10 07:06 project_notes.txt<br>
+ubuntu@ip-172-31-36-175:~/devops_workspace$ ls -l
+total 0
+-rw-rw-r-- 1 ubuntu ubuntu 0 Nov 10 07:06 project_notes.txt
 
-🔹 Set owner: full, group: read, others: none<br>
-ubuntu@ip-172-31-36-175:~/devops_workspace$ chmod 740 project_notes.txt<br>
-ubuntu@ip-172-31-36-175:~/devops_workspace$ ls -l<br>
-total 0<br>
--rwxr----- 1 ubuntu ubuntu 0 Nov 10 07:06 project_notes.txt<br>
+🔹 Set owner: full, group: read, others: none
+ubuntu@ip-172-31-36-175:~/devops_workspace$ chmod 740 project_notes.txt
+ubuntu@ip-172-31-36-175:~/devops_workspace$ ls -l
+total 0
+-rwxr----- 1 ubuntu ubuntu 0 Nov 10 07:06 project_notes.txt
 
-**✅ 3. Log File Analysis (grep, awk, sed)**<br>
+**✅ 3. Log File Analysis (grep, awk, sed)**
 
-🔹 Navigate to logs<br>
-ubuntu@ip-172-31-36-175:~$ cd ~/logs<br>
-ubuntu@ip-172-31-36-175:~/logs$ ls<br>
-app.log  auth_failure_ips.txt<br>
+🔹 Navigate to logs
+ubuntu@ip-172-31-36-175:~$ cd ~/logs
+ubuntu@ip-172-31-36-175:~/logs$ ls
+app.log  auth_failure_ips.txt
 
-🔹 Search for errors<br>
-ubuntu@ip-172-31-36-175:~/logs$ grep -i "error" app.log<br>
+🔹 Search for errors
+ubuntu@ip-172-31-36-175:~/logs$ grep -i "error" app.log
 
-🔹 Search authentication failures<br>
-ubuntu@ip-172-31-36-175:~/logs$ grep -i "authentication failure" app.log<br>
-Jun 14 15:16:01 combo sshd(pam_unix)[19939]: authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=218.188.2.4<br>
-Jun 14 15:16:02 combo sshd(pam_unix)[19937]: authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=218.188.2.4<br>
+🔹 Search authentication failures
+ubuntu@ip-172-31-36-175:~/logs$ grep -i "authentication failure" app.log
+Jun 14 15:16:01 combo sshd(pam_unix)[19939]: authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=218.188.2.4
+Jun 14 15:16:02 combo sshd(pam_unix)[19937]: authentication failure; logname= uid=0 euid=0 tty=NODEVssh ruser= rhost=218.188.2.4
 
-🔹 Extract timestamps and IP with awk<br>
-ubuntu@ip-172-31-36-175:~/logs$ awk '/authentication failure/{print $1,$2,$3,$12,$13,$14,$15}' app.log<br>
-Jun 14 15:16:01 ruser= rhost=218.188.2.4<br>
-Jun 14 15:16:02 ruser= rhost=218.188.2.4<br>
+🔹 Extract timestamps and IP with awk
+ubuntu@ip-172-31-36-175:~/logs$ awk '/authentication failure/{print $1,$2,$3,$12,$13,$14,$15}' app.log
+Jun 14 15:16:01 ruser= rhost=218.188.2.4
+Jun 14 15:16:02 ruser= rhost=218.188.2.4
 
-🔹 Save extracted data<br>
-ubuntu@ip-172-31-36-175:~/logs$ awk '/authentication failure/{print $1,$2,$3,$12,$13,$14,$15}' app.log > falied_ips.txt<br>
+🔹 Save extracted data<
+ubuntu@ip-172-31-36-175:~/logs$ awk '/authentication failure/{print $1,$2,$3,$12,$13,$14,$15}' app.log > falied_ips.txt
 
-🔹 Mask IP addresses using sed<br>
-ubuntu@ip-172-31-36-175:~/logs$ sed "s/rhost/[REDACTED]/g" falied_ips.txt<br>
-Jun 14 15:16:01 ruser= [REDACTED]=218.188.2.4<br>
-Jun 14 15:16:02 ruser= [REDACTED]=218.188.2.4<br>
-Jun 15 02:04:59 ruser= [REDACTED]=220-135-151-1.hinet-ip.hinet.net user=root<br>
+🔹 Mask IP addresses using sed
+ubuntu@ip-172-31-36-175:~/logs$ sed "s/rhost/[REDACTED]/g" falied_ips.txt
+Jun 14 15:16:01 ruser= [REDACTED]=218.188.2.4
+Jun 14 15:16:02 ruser= [REDACTED]=218.188.2.4
+Jun 15 02:04:59 ruser= [REDACTED]=220-135-151-1.hinet-ip.hinet.net user=root
 
-🔹 Most frequent log entries<br>
-ubuntu@ip-172-31-36-175:~/logs$ awk '{print $0}' app.log | sort | uniq -c | sort -nr | head -10<br>
+🔹 Most frequent log entries
+ubuntu@ip-172-31-36-175:~/logs$ awk '{print $0}' app.log | sort | uniq -c | sort -nr | head -10
 
-**✅ 4. Process Management & Monitoring**<br>
+**✅ 4. Process Management & Monitoring**
 
-🔹 Start a background process<br>
-ubuntu@ip-172-31-36-175:~$ ping google.com > oing_test.log &<br>
+🔹 Start a background process
+ubuntu@ip-172-31-36-175:~$ ping google.com > oing_test.log &
 
-🔹 Monitor processes<br>
-ubuntu@ip-172-31-36-175:~$ ps aux | grep ping<br>
-ubuntu@ip-172-31-36-175:~$ top<br>
-ubuntu@ip-172-31-36-175:~$ htop<br>
+🔹 Monitor processes
+ubuntu@ip-172-31-36-175:~$ ps aux | grep ping
+ubuntu@ip-172-31-36-175:~$ top
+ubuntu@ip-172-31-36-175:~$ htop
 
-🔹 Kill the process<br>
-ubuntu@ip-172-31-36-175:~$ kill 1935<br>
-ubuntu@ip-172-31-36-175:~$ ps aux | grep ping<br>
+🔹 Kill the process
+ubuntu@ip-172-31-36-175:~$ kill 1935
+ubuntu@ip-172-31-36-175:~$ ps aux | grep ping
 
-🔹 Verify output<br>
-ubuntu@ip-172-31-36-175:~$ tail oing_test.log<br>
+🔹 Verify output
+ubuntu@ip-172-31-36-175:~$ tail oing_test.log
 
-**✅ 5. Automating Backups with Shell Script + Cron**<br>
+**✅ 5. Automating Backups with Shell Script + Cron**
 
-🔹 Create backups directory & script<br>
-ubuntu@ip-172-31-36-175:~$ sudo mkdir -p /backups<br>
-ubuntu@ip-172-31-36-175:~$ sudo nano /backups/backup_devops_workspace.sh<br>
-backup_devops_workspace.sh<br>
-#!/bin/bash<br>
-tar -czf /backups/backup_$(date +%F).tar.gz ~/devops_workspace<br>
+🔹 Create backups directory & script
+ubuntu@ip-172-31-36-175:~$ sudo mkdir -p /backups
+ubuntu@ip-172-31-36-175:~$ sudo nano /backups/backup_devops_workspace.sh
+backup_devops_workspace.sh
+#!/bin/bash
+tar -czf /backups/backup_$(date +%F).tar.gz ~/devops_workspace
 
-if [ $? -eq 0 ]; then<br>
-    echo "Backup completed successfully: /backups/backup_$(date +%F).tar.gz"<br>
+if [ $? -eq 0 ]; then
+    echo "Backup completed successfully: /backups/backup_$(date +%F).tar.gz"
 else<br>
-    echo "Backup failed!"<br>
-fi<br>
+    echo "Backup failed!"
+fi
 
-🔹 Make script executable<br>
-ubuntu@ip-172-31-36-175:~$ sudo chmod +x /backups/backup_devops_workspace.sh<br>
+🔹 Make script executable
+ubuntu@ip-172-31-36-175:~$ sudo chmod +x /backups/backup_devops_workspace.sh
 
-🔹 Schedule with cron (daily at 02:00 AM)<br>
-ubuntu@ip-172-31-36-175:~$ sudo crontab -e<br>
-Add:<br>
-0 2 * * * /backups/backup_devops_workspace.sh >> /backups/backup_log.txt 2>&1<br>
+🔹 Schedule with cron (daily at 02:00 AM)
+ubuntu@ip-172-31-36-175:~$ sudo crontab -e
+Add:
+0 2 * * * /backups/backup_devops_workspace.sh >> /backups/backup_log.txt 2>&1
